=begin
Q: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Ans: Keep adding numbers when ever they are even. i = 1, prev = prev + i -> Updates previous number & i = prev

=end

sum = 0
prev = 0
i = 1
while i <= 4000000 do
    sum +=i if (i % 2 == 0)
    prev = prev + i
    i = prev
end
puts sum 