=begin
Q: The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Ans: Basically we have to find a triangle number which will have over 500 divisors. We can find it from prime number. Ex: If we take LCM(or Prime division) of 28 we get 2^2 * 7^1. We can get the divisors count by adding 1 to power and then multiplying the powers i.e., Here (2+1)*(1+1) = 6. Thus 6 Divisors. So we can generate all triangle numbers from 1 till divisor count <= 500. "tn" are the triangle numbers. prime_division method gives an 3D array of one divisor prime and other of power. See ruby docs for more info.

=end

require 'prime'
class Integer
    def divisor_count
        sum = 1
        self.prime_division.each do |x|
            sum *= (x[1] + 1)
        end
        sum
    end
end
i = 1
tn = 1
while(tn.divisor_count <= 500) do
    i += 1
    tn += i
end
puts tn